//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RS2015_Checkin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checkin
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string School { get; set; }
        public string Department { get; set; }
        public string Grade { get; set; }
        public bool Checkin1 { get; set; }
    }
}
